"""
GraphRAG service.

Central orchestration service for the Enterprise Knowledge Assistant.

Responsibilities

1. Hybrid Retrieval
2. Context Construction
3. Prompt Construction
4. Answer Generation
5. Citation Generation
6. Confidence Scoring
7. Hallucination Validation
"""

from __future__ import annotations

from dataclasses import dataclass

from app.core.logging_config import get_logger

from app.graphrag.answer_generator import (
    answer_generator,
)

from app.graphrag.context_builder import (
    context_builder,
)


from app.graphrag.prompt_builder import (
    prompt_builder,
)

from app.retrieval.hybrid_retriever import (
    hybrid_retriever,
)

logger = get_logger(__name__)


@dataclass(slots=True)
class GraphRAGResponse:
    """
    GraphRAG execution result.

    This class intentionally contains only the outputs generated by the
    GraphRAG pipeline. Citation generation and validation are handled
    later by the LangGraph workflow.
    """

    answer: str

    vector_results: list

    graph_results: list

    keyword_results: list


class GraphRAGService:
    """
    Enterprise GraphRAG orchestration service.
    """

    def __init__(self) -> None:

        self._retriever = hybrid_retriever

        self._context_builder = context_builder

        self._prompt_builder = prompt_builder

        self._answer_generator = answer_generator

        

    def query(
        self,
        question: str,
        top_k: int = 5,
    ) -> GraphRAGResponse:
        """
        Execute the complete GraphRAG workflow.

        Args:
            question:
                User question.

            top_k:
                Maximum retrieval results.

        Returns:
            GraphRAGResponse
        """

        logger.info(
            "Starting GraphRAG workflow."
        )

        # --------------------------------------------------
        # Hybrid Retrieval
        # --------------------------------------------------

        retrieval_result = self._retriever.retrieve(
            query=question,
            top_k=top_k,
        )

        vector_results = retrieval_result.get(
            "vector",
            [],
        )

        graph_results = retrieval_result.get(
            "graph",
            [],
        )

        keyword_results = retrieval_result.get(
            "keyword",
            [],
        )

        logger.info(
            "Retrieved %d vector, %d graph and %d keyword results.",
            len(vector_results),
            len(graph_results),
            len(keyword_results),
        )

        # --------------------------------------------------
        # Build Enterprise Context
        # --------------------------------------------------

        context = self._context_builder.build(
            vector_results,
        )

        logger.info(
            "Enterprise context constructed."
        )

        # --------------------------------------------------
        # Build Prompt
        # --------------------------------------------------

        prompt = self._prompt_builder.build(
            query=question,
            context=context,
        )

        logger.info(
            "Prompt successfully generated."
        )

        # --------------------------------------------------
        # Generate Answer
        # --------------------------------------------------

        answer = self._answer_generator.generate(
            prompt,
        )

        logger.info(
            "LLM answer generated."
        )
            # --------------------------------------------------
        # Build Citations
        # --------------------------------------------------

        
        # --------------------------------------------------
        # Workflow Completed
        # --------------------------------------------------

        logger.info(
            "GraphRAG workflow completed successfully."
        )

        return GraphRAGResponse(
            answer=answer,
            vector_results=vector_results,
            graph_results=graph_results,
            keyword_results=keyword_results,
        )


graphrag_service = GraphRAGService()    